### ISSUE TITLE
edgelib or sample project won't compile at all

### ISSUE THREAD

**Issue by liuxuan30** [elementsinteractive/edgelib#1]
Hi there,

Just let you know your neither edgelib nor sample project for iOS could compile at all. Please fix it. Or make a release of the library.

**Comment by woutertenbrink** [comment]
Hi, thanks for your comment. Please note that the library has not been touched in six years (the days of iOS 5). The library source code is not supported nor maintained anymore. You are invited to update! :)

**Comment by liuxuan30** [comment]
does this mean edgelib is.. EOL?

**Comment by woutertenbrink** [comment]
Correct. The library is not maintained anymore since 2012.

**Comment by liuxuan30** [comment]
thanks for clarification!
